### ISSUE TITLE
make heap general

### ISSUE THREAD

**Issue by cly753** [ntuorangejuice/cheat-sheet#11]

**Comment by imdreamrunner** [comment]
你说说 手写的heap还是那几个stl的lib?

**Comment by cly753** [comment]
手写的。。因为stl的不知道怎么改一个已经存在的element然后 reheap。。。

**Comment by imdreamrunner** [comment]
heap的设计应该不可以reheap的对不对。。。

**Comment by cly753** [comment]
就是改一个element的priority 然后应该可以用sift_up(heapify_up) sift_down(heapify_down) 把它移到对的位置吧？

**Comment by cly753** [comment]
反正set最好了.. 拿出来再放进去..
